config/routes.rb
DoodleOrDieClone::Application.routes.draw do
  root to: "static_pages#root"

  resource :session, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show]

  resources :rooms, :only => [:index, :show, :create, :update], defaults: {:format => :json} do
    get "fetch_step", to: "steps#fetch_next_step"
    put "fetch_step/:id", to: "steps#skip"

    resource :timeline, :only => [:show, :create]
  end

  resources :chains, :only => [:show, :update, :create] do
    resources :steps, :only => [:create]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  email           :string(255)
#  password_digest :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password, :password2

  validate :passwords_match
  validates :email, :uniqueness => true, :allow_blank => true
  validates :username, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :password_digest, :presence => { :message => "Password can't be blank" }

  has_many :sessions
  has_many :steps

  def steps_for_room(room)
    room_id = room.is_a?(Room) ? room.id : room

    self.steps.joins(:chain).where('chains.room_id = ?', room)
  end


  def password2=(confirmation_password)
    @password2 = confirmation_password
  end

  def password=(unencrypted_password)
    @password = unencrypted_password
    self.password_digest = BCrypt::Password.create(unencrypted_password)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def self.find_by_credentials(identifer, password)
    user = User.find_by_username(identifer)
    user = User.find_by_email(identifer) unless user
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  private

  def passwords_match
    errors.add(:password, "mismatch") unless self.password == self.password2
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    #returns all chains for a particular user
    #helper method to select last few steps
    @user = User.find(params[:id])
    render json: @user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to "#/rooms/1"
    else
      flash.now[:errors] = @user.errors.full_messages
      p @user.errors.full_messages
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password2)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="sign-up-header">Sign Up</div>

<br>

<div class="sign-up-form">  
  <form action="<%=users_url%>" method="POST" accept-charset="utf-8">
    <input type="hidden"
           name="authenticity_token"
           value="<%=form_authenticity_token%>">

  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" name="user[username]"
           class="form-control"
           value="<%=@user.username%>" id="username"
           placeholder="Your Username">
           
  </div>

  <div class="form-group">
    <label for="email">Email(optional)</label>
    <input type="text" name="user[email]"
           class="form-control" 
           value="<%=@user.email%>" id="email"
           placeholder="Yep. Optional.">
  </div>

  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" name="user[password]" id="password"
    placeholder="6 Char. Minimum">
  </div>

  <div class="form-group">
    <label for="confirm_password">Confirm Password</label>
    <input type="password" class="form-control" name="user[password2]" id="confirm_password"
    placeholder="Same">
  </div>

    <p><input class="btn-primary animate-thing" type="submit" value="Sign Up"></p>
  </form>
</div>