config/routes.rb
DoodleOrDieClone::Application.routes.draw do
  root to: "static_pages#root"

  resource :session, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show]

  resources :rooms, :only => [:index, :show, :create, :update], defaults: {:format => :json} do
    get "fetch_step", to: "steps#fetch_next_step"
    put "fetch_step/:id", to: "steps#skip"

    resource :timeline, :only => [:show, :create]
  end

  resources :chains, :only => [:show, :update, :create] do
    resources :steps, :only => [:create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoodleOrDont</title>
  <link href='http://fonts.googleapis.com/css?family=Elsie:400,900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Peralta|Elsie:400,900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/#">DoodleOrDont</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <% if logged_in? %>

<!-- Signed in as: <%=current_user.username%><%= button_to "Sign Out", session_url, :method => :delete %> -->

      <ul class="nav navbar-nav">
        <li><a href="/#/rooms/1">Explore</a></li>
        <li><a href="/#/rooms/1/play">Play</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.username%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <!-- <li><a href="#">Your Doodles (broken :[ sorry) </a></li> -->
              <!-- <li class="divider"></li> -->
              <li id="logout-btn"><%= button_to "Log Out", session_url, method: :delete %></li>
            </ul>
        </li>
      </ul>

  <% else %>
      <ul class="nav navbar-nav">
        <li><a href="/#/rooms/1">Explore</a></li>
        <li><a href="<%=new_user_url%>">Create Account</a></li>
        <li><a href="<%=new_session_url%>">Sign In</a></li>
        <!-- <li><a href="/#">About</a></li> -->
      </ul>
  <% end %>

  <!-- class="active" on li to make it darker -->

  </div>
  </div>
</nav>

<%= yield %>

<%= javascript_include_tag "application" %>

</body>
</html>